---
- name: Deploy Database Services
  hosts: database_nodes
  become: true
  vars:
    mssql_sa_password: "{{ lookup('env', 'MSSQL_SA_PASSWORD') | default('password123!', true) }}"
  tasks:
    - name: Run MS SQL Server Docker Container
      community.docker.docker_container:
        name: mssql-server
        image: mcr.microsoft.com/mssql/server:2022-latest
        state: started
        restart_policy: always
        env:
          ACCEPT_EULA: "Y"
          MSSQL_SA_PASSWORD: "{{ mssql_sa_password }}"
        published_ports:
          - "1433:1433"