services:
  wallet-api:
    image: miniwallet-api:latest
    container_name: miniwallet_api_container

    build:
      context: ../src
      dockerfile: MiniWalletSystemApi/Dockerfile

    ports:
      - "8084:8084"

    volumes:
      - wallet_api_logs:/app/Logs

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8084

      OpenBao__Address: ${OPENBAO_ADDR}
      OpenBao__RoleId: ${OPENBAO_ROLE_ID}
      OpenBao__SecretId: ${OPENBAO_SECRET_ID}
      OpenBao__SecretPath: secret/data/simplewallet/dev

volumes:
  wallet_api_logs: